apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-api-server"
  labels:
    app: api-server
    microservice: "{{ .Release.Name }}"
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: api-server
    microservice: "{{ .Release.Name }}"
