port: 3000

postgresql:
  auth:
    database: "wlosiara_pl_products_service"
    username: "wlosiara-pl-products-service"
    password: null # required
  primary:
    initdb:
      scriptsConfigMap: "wlosiara-pl-products-service-postgresql-initdb-scripts"
      user: "wlosiara-pl-products-service"
      password: null # required
    resources:
      requests:
        cpu: "50m"
        memory: "128Mi"
    persistence:
      size: "1Gi"

image:
  dockerRegistry:
    host: null # required

usersMicroserviceBaseUrl: null # required

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "100m"
    memory: "256Mi"
