port: 3000

postgresql:
  auth:
    database: "wlosiara-pl-products-service"
    username: "wlosiara-pl-products-service"
  primary:
    initdb:
      scripts-configmap: "wlosiara-pl-products-service-initdb-scripts"

image:
  dockerRegistry:
    host: null # required
