port: 3000

postgresql:
  auth:
    database: "products-service"
    username: "products-service"
  primary:
    initdb:
      scripts-configmap: "products-service-initdb-scripts"

image:
  repository: null
